# Generated by Django 4.1.4 on 2022-12-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lfipayload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payload', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Xsspayload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payload', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Xss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xssurl', models.CharField(max_length=500)),
                ('Xssid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xss.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirecturl', models.CharField(max_length=500)),
                ('Redirectid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xss.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Lfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfiurl', models.CharField(max_length=500)),
                ('Lfiid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xss.domain')),
            ],
        ),
    ]
