# Generated by Django 4.1.4 on 2023-02-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0002_alter_lfipayload_id_alter_xsspayload_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hstpayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubdomainTakeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sturl', models.CharField(max_length=500)),
                ('Stid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xss.domain')),
            ],
        ),
    ]
